components: {}
info:
  contact:
    email: contact@1forge.com
    name: 1Forge
    url: http://1forge.com
  description: Stock and Forex Data and Realtime Quotes
  title: 1Forge Finance APIs
  version: 0.0.1
  x-apisguru-categories:
  - financial
  x-logo:
    backgroundColor: '#24292e'
    url: https://api.apis.guru/v2/cache/logo/https_1forge.com_assets_images_f-blue.svg
  x-origin:
  - format: swagger
    url: http://1forge.com/openapi.json
    version: '2.0'
  x-providerName: 1forge.com
openapi: 3.0.1
paths:
  /quotes:
    get:
      description: Get quotes
      externalDocs:
        description: Find out more
        url: http://1forge.com/forex-data-api
      responses:
        '200':
          content: {}
          description: A list of quotes
      summary: Get quotes for all symbols
      tags:
      - forex
      - finance
      - quotes
  /symbols:
    get:
      description: Symbol List
      externalDocs:
        description: Find out more
        url: http://1forge.com/forex-data-api
      responses:
        '200':
          content:
            application/json:
              schema:
                example:
                - EURUSD
                - GBPJPY
                - AUDUSD
                items:
                  type: string
                type: array
          description: A list of symbols
      summary: Get a list of symbols for which we provide real-time quotes
      tags:
      - forex
      - finance
      - quotes
servers:
- url: https://1forge.com/forex-quotes
- url: http://1forge.com/forex-quotes
x-original-swagger-version: '2.0'
