components:
  schemas:
    Error:
      properties:
        code:
          format: int32
          type: integer
        fields:
          type: string
        message:
          type: string
      type: object
    User:
      properties:
        access_token:
          description: Generated JWT for the user.
          type: string
        email:
          description: Email of the user.
          type: string
      type: object
info:
  description: API to access different features for 2rr34 project.
  title: 2rr34 API
  version: v1
openapi: 3.0.1
paths:
  /login:
    post:
      description: Allows to login to 2rr34
      parameters:
      - description: Email of user
        in: query
        name: email
        required: true
        schema:
          format: email
          type: string
      - description: Password of user
        in: query
        name: password
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: An array of products
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Login endpoint
      tags:
      - Auth
  /signup:
    post:
      description: Allows to signup to 2rr34
      parameters:
      - description: Email of user
        in: query
        name: email
        required: true
        schema:
          format: email
          type: string
      - description: Password of user
        in: query
        name: password
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: User object
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error
      summary: Signup endpoint
      tags:
      - Auth
servers:
- url: https://virtserver.swaggerhub.com/rraspo/2rr34/v1
x-original-swagger-version: '2.0'
